# Generated by Django 6.0.2 on 2026-02-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(to='competition_app.question'),
        ),
    ]
