# Generated by Django 6.0.2 on 2026-02-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0002_quizsession_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
